### PR TITLE
update ltx to v0.3.2

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by dhruvbird** [comment]
What does this fix/impact if any/and why is it needed?
Maybe update the commit message with this info. so that we know the motivation.
Also, has it been tested (only the websocket code path currently uses ltx - everything else uses node-expat, and we don't have unit tests for the websocket server).

**Comment by flosse** [comment]
There are some tiny bugfixes but you're right I cannot judge the importance. As long @astro or @lloydwatkin don't explicitly suggest an update don't mind anymore ;-)

**Comment by dhruvbird** [comment]
@flosse Makes sense. I'll park this PR for now - unless @astro or @lloydwatkin think otherwise.

**Comment by lloydwatkin** [comment]
The only changes with ltx from 0.2.X to 0.3.2 were around browserify, adding some texts, and fixing a partially parsed attributes bug (https://github.com/node-xmpp/ltx/commit/758cd644f87e450e0b425382638d34d2a3b05dc4).

An update wouldn't hurt but the gains you are getting are minimal (since most of the updates are for the browser).

**Pull request merged**
